{"version": "0.1", "tests": [{"id": "functional.test_toolbox.TestForTool_SRS_obisindicators.test_tool_000000", "has_data": true, "data": {"tool_id": "SRS_obisindicators", "tool_version": "0.0.0", "test_index": 0, "time_seconds": 2.840200662612915, "execution_problem": "Input staging problem: Test input file (occ_at.tabular) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/usr/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1099, in verify_tool\n    tool_version=tool_version,\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 86, in stage_data_in_history\n    tool_version=tool_version)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (occ_at.tabular) cannot be found.\n-------------------- >> begin captured stdout << ---------------------\nExecuting git clone 'https://github.com/galaxyproject/galaxy-test-data.git' 'test-data-cache/ad1daf4e1504da1acd42c088c6f49be6'\nExecuting git --work-tree test-data-cache/ad1daf4e1504da1acd42c088c6f49be6 --git-dir test-data-cache/ad1daf4e1504da1acd42c088c6f49be6/.git fetch && git --work-tree test-data-cache/ad1daf4e1504da1acd42c088c6f49be6 --git-dir test-data-cache/ad1daf4e1504da1acd42c088c6f49be6/.git merge origin/master\n\n--------------------- >> end captured stdout << ----------------------\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:55]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}, {"id": "functional.test_toolbox.TestForTool_SRS_reading_data.test_tool_000000", "has_data": true, "data": {"tool_id": "SRS_reading_data", "tool_version": "@VERSION@", "test_index": 0, "time_seconds": 0.03789472579956055, "inputs": {}, "execution_problem": "parameter 'input_1': specify a dataset of the required format / build for parameter, parameter 'input_2': specify a dataset of the required format / build for parameter", "dynamic_param_error": false, "status": "error", "problem_type": "galaxy.tool_util.verify.interactor.RunToolException", "problem_log": "  File \"/usr/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/usr/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1112, in verify_tool\n    raise e\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1105, in verify_tool\n    tool_response = galaxy_interactor.run_tool(testdef, test_history, resource_parameters=resource_parameters)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 469, in run_tool\n    submit_response_object = ensure_tool_run_response_okay(submit_response, \"execute tool\", inputs_tree)\n  File \"/tmp/tmpmxhf2ugy/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 817, in ensure_tool_run_response_okay\n    raise RunToolException(message, inputs, dynamic_param_error=dynamic_param_error)\nparameter 'input_1': specify a dataset of the required format / build for parameter, parameter 'input_2': specify a dataset of the required format / build for parameter\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:61]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}], "summary": {"num_tests": 2, "num_failures": 1, "num_errors": 1, "num_skips": 0}, "exit_code": 1}